---
abstract: 'Build and install the GNU build system.'
author:
  - 'Richard Simões <rsimoes AT cpan DOT org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
  Test::Requires: 0
configure_requires:
  Archive::Tar: 0
  ExtUtils::CChecker: 0
  File::ShareDir: 0
  IPC::Cmd: 0
  Module::Build: 0.3601
  Net::FTP: 0
  Test::Requires: 0
  perl: 5.008_008
  version: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300013, CPAN::Meta::Converter version 2.120900'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-Autotools
requires:
  perl: 5.008
resources:
  bugtracker: https://github.com/rsimoes/alien-autotools/issues
  homepage: https://metacpan.org/release/Alien-Autotools
  repository: git://github.com/rsimoes/alien-autotools.git
version: v0.0.3
